minimumReleaseAge: 10080 # 1 week

allowBuilds:
  "@tailwindcss/oxide": true
  esbuild: true
  msw: false
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  # Renovate security update: next@16.2.6
  - next@16.2.6
