minimumReleaseAge: 10080

minimumReleaseAgeExclude:
  - "oxfmt"
  - "@oxlint/*"
  - "@oxfmt/*"
  - "@oxlint-tsgolint/*"
  # Renovate security update: next@16.2.3
  - next@16.2.3
allowBuilds:
  "@tailwindcss/oxide": true
  esbuild: true
  msw: false
  sharp: true
  unrs-resolver: true
