minimumReleaseAge: 10080

minimumReleaseAgeExclude:
  - "oxfmt"
  - "@oxlint/*"
  - "@oxfmt/*"
  - "@oxlint-tsgolint/*"

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - "esbuild"
  - "sharp"
  - "unrs-resolver"
