export type DefaultsValue = boolean | number | string;

export interface DefaultsOption {
  defaultValue: DefaultsValue;
  desc: string;
  group: string;
  id: string;
  path: readonly string[];
  recommended?: boolean;
  title: string;
  type: "boolean" | "enum" | "number" | "text";
  values?: readonly {
    label: string;
    value: DefaultsValue;
  }[];
}

export const DEFAULTS_OPTIONS = [
  {
    defaultValue: true,
    desc: "Finder で拡張子を常に表示する。",
    group: "Finder",
    id: "finder.AppleShowAllExtensions",
    path: ["finder", "AppleShowAllExtensions"],
    recommended: true,
    title: "すべてのファイル拡張子を表示",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "Finder で dotfile などの隠しファイルを表示する。",
    group: "Finder",
    id: "finder.AppleShowAllFiles",
    path: ["finder", "AppleShowAllFiles"],
    recommended: true,
    title: "隠しファイルを表示",
    type: "boolean",
  },
  {
    defaultValue: false,
    desc: "デスクトップに Finder アイコンを表示するかを切り替える。",
    group: "Finder",
    id: "finder.CreateDesktop",
    path: ["finder", "CreateDesktop"],
    title: "デスクトップアイコンの表示",
    type: "boolean",
  },
  {
    defaultValue: "SCcf",
    desc: "Finder 検索の初期範囲を現在のフォルダにする。",
    group: "Finder",
    id: "finder.FXDefaultSearchScope",
    path: ["finder", "FXDefaultSearchScope"],
    recommended: true,
    title: "検索範囲を現在のフォルダにする",
    type: "enum",
    values: [
      {
        label: "current folder",
        value: "SCcf",
      },
      {
        label: "everywhere",
        value: "SCev",
      },
      {
        label: "previous scope",
        value: "SCsp",
      },
    ],
  },
  {
    defaultValue: false,
    desc: "ファイル拡張子の変更時に警告を表示する。",
    group: "Finder",
    id: "finder.FXEnableExtensionChangeWarning",
    path: ["finder", "FXEnableExtensionChangeWarning"],
    recommended: true,
    title: "拡張子変更の警告",
    type: "boolean",
  },
  {
    defaultValue: "Nlsv",
    desc: "新しい Finder ウィンドウの表示形式を選ぶ。",
    group: "Finder",
    id: "finder.FXPreferredViewStyle",
    path: ["finder", "FXPreferredViewStyle"],
    recommended: true,
    title: "Finder の標準表示形式",
    type: "enum",
    values: [
      {
        label: "Icon view",
        value: "icnv",
      },
      {
        label: "List view",
        value: "Nlsv",
      },
      {
        label: "Column view",
        value: "clmv",
      },
      {
        label: "Gallery view",
        value: "Flwv",
      },
    ],
  },
  {
    defaultValue: true,
    desc: "ゴミ箱内の古い項目を自動で削除する。",
    group: "Finder",
    id: "finder.FXRemoveOldTrashItems",
    path: ["finder", "FXRemoveOldTrashItems"],
    recommended: true,
    title: "30 日後にゴミ箱から削除",
    type: "boolean",
  },
  {
    defaultValue: "Home",
    desc: "Finder ウィンドウを開いたときの初期表示先を選ぶ。",
    group: "Finder",
    id: "finder.NewWindowTarget",
    path: ["finder", "NewWindowTarget"],
    title: "新規 Finder ウィンドウの場所",
    type: "enum",
    values: [
      {
        label: "Home",
        value: "Home",
      },
      {
        label: "Desktop",
        value: "Desktop",
      },
      {
        label: "Documents",
        value: "Documents",
      },
      {
        label: "Recents",
        value: "Recents",
      },
      {
        label: "iCloud Drive",
        value: "iCloud Drive",
      },
      {
        label: "Other",
        value: "Other",
      },
    ],
  },
  {
    defaultValue: "file:///Users/you",
    desc: "NewWindowTarget が Other のときに開く URI。",
    group: "Finder",
    id: "finder.NewWindowTargetPath",
    path: ["finder", "NewWindowTargetPath"],
    title: "新規 Finder ウィンドウの Other パス",
    type: "text",
  },
  {
    defaultValue: true,
    desc: "Finder の Quit メニューを表示する。",
    group: "Finder",
    id: "finder.QuitMenuItem",
    path: ["finder", "QuitMenuItem"],
    title: "Finder を終了できるようにする",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "Finder ウィンドウ下部にパスバーを表示する。",
    group: "Finder",
    id: "finder.ShowPathbar",
    path: ["finder", "ShowPathbar"],
    recommended: true,
    title: "パスバーを表示",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "Finder ウィンドウ下部に項目数や空き容量を表示する。",
    group: "Finder",
    id: "finder.ShowStatusBar",
    path: ["finder", "ShowStatusBar"],
    recommended: true,
    title: "ステータスバーを表示",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "Finder のカラム表示でファイル名に合わせて幅を調整する。",
    group: "Finder",
    id: "finder._FXEnableColumnAutoSizing",
    path: ["finder", "_FXEnableColumnAutoSizing"],
    title: "カラム幅を自動調整",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "Finder ウィンドウタイトルにフルパスを表示する。",
    group: "Finder",
    id: "finder._FXShowPosixPathInTitle",
    path: ["finder", "_FXShowPosixPathInTitle"],
    title: "タイトルに POSIX パスを表示",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "Finder で名前順ソート時にフォルダを先頭にする。",
    group: "Finder",
    id: "finder._FXSortFoldersFirst",
    path: ["finder", "_FXSortFoldersFirst"],
    recommended: true,
    title: "フォルダを先頭に並べる",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "デスクトップの名前順ソートでもフォルダを先頭にする。",
    group: "Finder",
    id: "finder._FXSortFoldersFirstOnDesktop",
    path: ["finder", "_FXSortFoldersFirstOnDesktop"],
    title: "デスクトップでもフォルダを先頭に並べる",
    type: "boolean",
  },
  {
    defaultValue: false,
    desc: "長押しでアクセント候補を出す代わりにキーリピートを使いやすくする。",
    group: "NSGlobalDomain",
    id: "NSGlobalDomain.ApplePressAndHoldEnabled",
    path: ["NSGlobalDomain", "ApplePressAndHoldEnabled"],
    recommended: true,
    title: "キー長押しのアクセント入力",
    type: "boolean",
  },
  {
    defaultValue: 15,
    desc: "キーを押し続けたときにリピートが始まるまでの待ち時間。",
    group: "NSGlobalDomain",
    id: "NSGlobalDomain.InitialKeyRepeat",
    path: ["NSGlobalDomain", "InitialKeyRepeat"],
    recommended: true,
    title: "キーリピート開始までの時間",
    type: "number",
  },
  {
    defaultValue: 2,
    desc: "キーリピートが始まった後の繰り返し速度。",
    group: "NSGlobalDomain",
    id: "NSGlobalDomain.KeyRepeat",
    path: ["NSGlobalDomain", "KeyRepeat"],
    recommended: true,
    title: "キーリピート速度",
    type: "number",
  },
  {
    defaultValue: true,
    desc: "グローバル設定として拡張子を表示する。",
    group: "NSGlobalDomain",
    id: "NSGlobalDomain.AppleShowAllExtensions",
    path: ["NSGlobalDomain", "AppleShowAllExtensions"],
    recommended: true,
    title: "全アプリで拡張子を表示",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "グローバル設定として隠しファイルを表示する。",
    group: "NSGlobalDomain",
    id: "NSGlobalDomain.AppleShowAllFiles",
    path: ["NSGlobalDomain", "AppleShowAllFiles"],
    title: "全アプリで隠しファイルを表示",
    type: "boolean",
  },
  {
    defaultValue: "Always",
    desc: "スクロールバーをいつ表示するかを選ぶ。",
    group: "NSGlobalDomain",
    id: "NSGlobalDomain.AppleShowScrollBars",
    path: ["NSGlobalDomain", "AppleShowScrollBars"],
    title: "スクロールバー表示",
    type: "enum",
    values: [
      {
        label: "Automatic",
        value: "Automatic",
      },
      {
        label: "Always",
        value: "Always",
      },
      {
        label: "When scrolling",
        value: "WhenScrolling",
      },
    ],
  },
  {
    defaultValue: false,
    desc: "アプリに既存ウィンドウがある Space へ自動移動する。",
    group: "NSGlobalDomain",
    id: "NSGlobalDomain.AppleSpacesSwitchOnActivate",
    path: ["NSGlobalDomain", "AppleSpacesSwitchOnActivate"],
    title: "アプリ切替時に Space を移動",
    type: "boolean",
  },
  {
    defaultValue: "manual",
    desc: "新しい書類を開くときのウィンドウタブ動作を選ぶ。",
    group: "NSGlobalDomain",
    id: "NSGlobalDomain.AppleWindowTabbingMode",
    path: ["NSGlobalDomain", "AppleWindowTabbingMode"],
    title: "新規書類のタブ化",
    type: "enum",
    values: [
      {
        label: "manual",
        value: "manual",
      },
      {
        label: "always",
        value: "always",
      },
      {
        label: "fullscreen",
        value: "fullscreen",
      },
    ],
  },
  {
    defaultValue: "Dark",
    desc: "外観を Dark にする。Light に戻す場合は defaults delete が必要。",
    group: "NSGlobalDomain",
    id: "NSGlobalDomain.AppleInterfaceStyle",
    path: ["NSGlobalDomain", "AppleInterfaceStyle"],
    title: "ダークモード",
    type: "enum",
    values: [
      {
        label: "Dark",
        value: "Dark",
      },
    ],
  },
  {
    defaultValue: true,
    desc: "ライト/ダークの外観を時刻などに応じて自動切替する。",
    group: "NSGlobalDomain",
    id: "NSGlobalDomain.AppleInterfaceStyleSwitchesAutomatically",
    path: ["NSGlobalDomain", "AppleInterfaceStyleSwitchesAutomatically"],
    title: "外観を自動切替",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "時刻表記を 24 時間制にする。",
    group: "NSGlobalDomain",
    id: "NSGlobalDomain.AppleICUForce24HourTime",
    path: ["NSGlobalDomain", "AppleICUForce24HourTime"],
    recommended: true,
    title: "24 時間表示",
    type: "boolean",
  },
  {
    defaultValue: "Centimeters",
    desc: "長さの単位を選ぶ。",
    group: "NSGlobalDomain",
    id: "NSGlobalDomain.AppleMeasurementUnits",
    path: ["NSGlobalDomain", "AppleMeasurementUnits"],
    title: "測定単位",
    type: "enum",
    values: [
      {
        label: "Centimeters",
        value: "Centimeters",
      },
      {
        label: "Inches",
        value: "Inches",
      },
    ],
  },
  {
    defaultValue: 1,
    desc: "メートル法を使う。",
    group: "NSGlobalDomain",
    id: "NSGlobalDomain.AppleMetricUnits",
    path: ["NSGlobalDomain", "AppleMetricUnits"],
    title: "メートル法",
    type: "enum",
    values: [
      {
        label: "enabled",
        value: 1,
      },
      {
        label: "disabled",
        value: 0,
      },
    ],
  },
  {
    defaultValue: "Celsius",
    desc: "温度表示の単位を選ぶ。",
    group: "NSGlobalDomain",
    id: "NSGlobalDomain.AppleTemperatureUnit",
    path: ["NSGlobalDomain", "AppleTemperatureUnit"],
    title: "温度単位",
    type: "enum",
    values: [
      {
        label: "Celsius",
        value: "Celsius",
      },
      {
        label: "Fahrenheit",
        value: "Fahrenheit",
      },
    ],
  },
  {
    defaultValue: false,
    desc: "テキスト入力時の自動大文字化を切り替える。",
    group: "NSGlobalDomain",
    id: "NSGlobalDomain.NSAutomaticCapitalizationEnabled",
    path: ["NSGlobalDomain", "NSAutomaticCapitalizationEnabled"],
    recommended: true,
    title: "自動大文字化",
    type: "boolean",
  },
  {
    defaultValue: false,
    desc: "ダッシュの自動置換を切り替える。",
    group: "NSGlobalDomain",
    id: "NSGlobalDomain.NSAutomaticDashSubstitutionEnabled",
    path: ["NSGlobalDomain", "NSAutomaticDashSubstitutionEnabled"],
    recommended: true,
    title: "スマートダッシュ",
    type: "boolean",
  },
  {
    defaultValue: false,
    desc: "テキスト入力時のインライン予測を切り替える。",
    group: "NSGlobalDomain",
    id: "NSGlobalDomain.NSAutomaticInlinePredictionEnabled",
    path: ["NSGlobalDomain", "NSAutomaticInlinePredictionEnabled"],
    title: "インライン予測変換",
    type: "boolean",
  },
  {
    defaultValue: false,
    desc: "スペース二回などによるピリオド置換を切り替える。",
    group: "NSGlobalDomain",
    id: "NSGlobalDomain.NSAutomaticPeriodSubstitutionEnabled",
    path: ["NSGlobalDomain", "NSAutomaticPeriodSubstitutionEnabled"],
    recommended: true,
    title: "ピリオド自動置換",
    type: "boolean",
  },
  {
    defaultValue: false,
    desc: "引用符の自動置換を切り替える。",
    group: "NSGlobalDomain",
    id: "NSGlobalDomain.NSAutomaticQuoteSubstitutionEnabled",
    path: ["NSGlobalDomain", "NSAutomaticQuoteSubstitutionEnabled"],
    recommended: true,
    title: "スマート引用符",
    type: "boolean",
  },
  {
    defaultValue: false,
    desc: "入力中の自動スペル補正を切り替える。",
    group: "NSGlobalDomain",
    id: "NSGlobalDomain.NSAutomaticSpellingCorrectionEnabled",
    path: ["NSGlobalDomain", "NSAutomaticSpellingCorrectionEnabled"],
    recommended: true,
    title: "自動スペル補正",
    type: "boolean",
  },
  {
    defaultValue: false,
    desc: "ウィンドウやポップオーバーを開閉するアニメーションを切り替える。",
    group: "NSGlobalDomain",
    id: "NSGlobalDomain.NSAutomaticWindowAnimationsEnabled",
    path: ["NSGlobalDomain", "NSAutomaticWindowAnimationsEnabled"],
    title: "ウィンドウアニメーション",
    type: "boolean",
  },
  {
    defaultValue: false,
    desc: "新規書類をデフォルトで iCloud に保存するかを切り替える。",
    group: "NSGlobalDomain",
    id: "NSGlobalDomain.NSDocumentSaveNewDocumentsToCloud",
    path: ["NSGlobalDomain", "NSDocumentSaveNewDocumentsToCloud"],
    recommended: true,
    title: "新規書類の iCloud 保存",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "保存ダイアログを展開状態で開く。",
    group: "NSGlobalDomain",
    id: "NSGlobalDomain.NSNavPanelExpandedStateForSaveMode",
    path: ["NSGlobalDomain", "NSNavPanelExpandedStateForSaveMode"],
    recommended: true,
    title: "保存パネルを展開",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "保存ダイアログを展開状態で開く追加設定。",
    group: "NSGlobalDomain",
    id: "NSGlobalDomain.NSNavPanelExpandedStateForSaveMode2",
    path: ["NSGlobalDomain", "NSNavPanelExpandedStateForSaveMode2"],
    recommended: true,
    title: "保存パネルを展開 2",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "印刷ダイアログを展開状態で開く。",
    group: "NSGlobalDomain",
    id: "NSGlobalDomain.PMPrintingExpandedStateForPrint",
    path: ["NSGlobalDomain", "PMPrintingExpandedStateForPrint"],
    title: "印刷パネルを展開",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "印刷ダイアログを展開状態で開く追加設定。",
    group: "NSGlobalDomain",
    id: "NSGlobalDomain.PMPrintingExpandedStateForPrint2",
    path: ["NSGlobalDomain", "PMPrintingExpandedStateForPrint2"],
    title: "印刷パネルを展開 2",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "ウィンドウ内を押しながらドラッグして移動できるようにする。",
    group: "NSGlobalDomain",
    id: "NSGlobalDomain.NSWindowShouldDragOnGesture",
    path: ["NSGlobalDomain", "NSWindowShouldDragOnGesture"],
    title: "ウィンドウの任意位置ドラッグ",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "F1, F2 などを標準ファンクションキーとして扱う。",
    group: "NSGlobalDomain",
    id: "NSGlobalDomain.com.apple.keyboard.fnState",
    path: ["NSGlobalDomain", "com.apple.keyboard.fnState"],
    recommended: true,
    title: "F1/F2 キーを標準ファンクションキーにする",
    type: "boolean",
  },
  {
    defaultValue: 0,
    desc: "音量変更時にフィードバック音を鳴らすかを切り替える。",
    group: "NSGlobalDomain",
    id: "NSGlobalDomain.com.apple.sound.beep.feedback",
    path: ["NSGlobalDomain", "com.apple.sound.beep.feedback"],
    title: "音量変更時のフィードバック音",
    type: "enum",
    values: [
      {
        label: "off",
        value: 0,
      },
      {
        label: "on",
        value: 1,
      },
    ],
  },
  {
    defaultValue: 0,
    desc: "システム警告音の音量を 0.0 から 1.0 で指定する。",
    group: "NSGlobalDomain",
    id: "NSGlobalDomain.com.apple.sound.beep.volume",
    path: ["NSGlobalDomain", "com.apple.sound.beep.volume"],
    title: "警告音の音量",
    type: "number",
  },
  {
    defaultValue: true,
    desc: "フォルダのスプリングロードを有効にする。",
    group: "NSGlobalDomain",
    id: "NSGlobalDomain.com.apple.springing.enabled",
    path: ["NSGlobalDomain", "com.apple.springing.enabled"],
    title: "スプリングロード",
    type: "boolean",
  },
  {
    defaultValue: 0,
    desc: "スプリングロードが発動するまでの遅延。",
    group: "NSGlobalDomain",
    id: "NSGlobalDomain.com.apple.springing.delay",
    path: ["NSGlobalDomain", "com.apple.springing.delay"],
    title: "スプリングロード遅延",
    type: "number",
  },
  {
    defaultValue: false,
    desc: "ナチュラルスクロール方向を使うかを切り替える。",
    group: "NSGlobalDomain",
    id: "NSGlobalDomain.com.apple.swipescrolldirection",
    path: ["NSGlobalDomain", "com.apple.swipescrolldirection"],
    title: "ナチュラルスクロール",
    type: "boolean",
  },
  {
    defaultValue: false,
    desc: "Force Click を有効にする。",
    group: "NSGlobalDomain",
    id: "NSGlobalDomain.com.apple.trackpad.forceClick",
    path: ["NSGlobalDomain", "com.apple.trackpad.forceClick"],
    title: "トラックパッド Force Click",
    type: "boolean",
  },
  {
    defaultValue: 2,
    desc: "トラックパッドの追従速度を 0 から 3 で指定する。",
    group: "NSGlobalDomain",
    id: "NSGlobalDomain.com.apple.trackpad.scaling",
    path: ["NSGlobalDomain", "com.apple.trackpad.scaling"],
    title: "トラックパッド追従速度",
    type: "number",
  },
  {
    defaultValue: true,
    desc: "Dock を自動で隠す。",
    group: "Dock",
    id: "dock.autohide",
    path: ["dock", "autohide"],
    recommended: true,
    title: "Dock を自動的に隠す",
    type: "boolean",
  },
  {
    defaultValue: 0,
    desc: "Dock が表示されるまでの遅延時間。",
    group: "Dock",
    id: "dock.autohide-delay",
    path: ["dock", "autohide-delay"],
    recommended: true,
    title: "Dock 表示の遅延",
    type: "number",
  },
  {
    defaultValue: 0.2,
    desc: "Dock の表示/非表示アニメーション速度。",
    group: "Dock",
    id: "dock.autohide-time-modifier",
    path: ["dock", "autohide-time-modifier"],
    recommended: true,
    title: "Dock アニメーション速度",
    type: "number",
  },
  {
    defaultValue: true,
    desc: "Command-Tab のアプリスイッチャー表示位置を切り替える。",
    group: "Dock",
    id: "dock.appswitcher-all-displays",
    path: ["dock", "appswitcher-all-displays"],
    title: "アプリスイッチャーを全ディスプレイに表示",
    type: "boolean",
  },
  {
    defaultValue: 0.15,
    desc: "Mission Control のアニメーション時間。",
    group: "Dock",
    id: "dock.expose-animation-duration",
    path: ["dock", "expose-animation-duration"],
    title: "Mission Control アニメーション速度",
    type: "number",
  },
  {
    defaultValue: true,
    desc: "Mission Control のウィンドウをアプリごとにまとめる。",
    group: "Dock",
    id: "dock.expose-group-apps",
    path: ["dock", "expose-group-apps"],
    title: "Mission Control でアプリ別にグループ化",
    type: "boolean",
  },
  {
    defaultValue: false,
    desc: "アプリ起動時の Dock アニメーションを切り替える。",
    group: "Dock",
    id: "dock.launchanim",
    path: ["dock", "launchanim"],
    title: "Dock から起動時のアニメーション",
    type: "boolean",
  },
  {
    defaultValue: false,
    desc: "Dock アイコンのマウスオーバー拡大を切り替える。",
    group: "Dock",
    id: "dock.magnification",
    path: ["dock", "magnification"],
    title: "Dock 拡大表示",
    type: "boolean",
  },
  {
    defaultValue: 48,
    desc: "Dock のアイコンサイズ。",
    group: "Dock",
    id: "dock.tilesize",
    path: ["dock", "tilesize"],
    title: "Dock アイコンサイズ",
    type: "number",
  },
  {
    defaultValue: 64,
    desc: "Dock 拡大表示を使う場合のアイコンサイズ。",
    group: "Dock",
    id: "dock.largesize",
    path: ["dock", "largesize"],
    title: "Dock 拡大時のアイコンサイズ",
    type: "number",
  },
  {
    defaultValue: "scale",
    desc: "ウィンドウ最小化/拡大時のエフェクトを選ぶ。",
    group: "Dock",
    id: "dock.mineffect",
    path: ["dock", "mineffect"],
    title: "ウィンドウ最小化エフェクト",
    type: "enum",
    values: [
      {
        label: "scale",
        value: "scale",
      },
      {
        label: "genie",
        value: "genie",
      },
      {
        label: "suck",
        value: "suck",
      },
    ],
  },
  {
    defaultValue: true,
    desc: "ウィンドウを Dock 右側ではなくアプリアイコンへ最小化する。",
    group: "Dock",
    id: "dock.minimize-to-application",
    path: ["dock", "minimize-to-application"],
    title: "アプリケーションアイコンへ最小化",
    type: "boolean",
  },
  {
    defaultValue: false,
    desc: "Spaces を最近使った順へ自動的に並べ替える。",
    group: "Dock",
    id: "dock.mru-spaces",
    path: ["dock", "mru-spaces"],
    recommended: true,
    title: "最近使った順に Spaces を並べ替え",
    type: "boolean",
  },
  {
    defaultValue: "bottom",
    desc: "Dock を表示する画面端を選ぶ。",
    group: "Dock",
    id: "dock.orientation",
    path: ["dock", "orientation"],
    title: "Dock の位置",
    type: "enum",
    values: [
      {
        label: "bottom",
        value: "bottom",
      },
      {
        label: "left",
        value: "left",
      },
      {
        label: "right",
        value: "right",
      },
    ],
  },
  {
    defaultValue: true,
    desc: "Dock アイコン上でスクロールして開いているウィンドウやスタックを表示する。",
    group: "Dock",
    id: "dock.scroll-to-open",
    path: ["dock", "scroll-to-open"],
    title: "Dock アイコンをスクロールで開く",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "Dock に起動中アプリのインジケータを表示する。",
    group: "Dock",
    id: "dock.show-process-indicators",
    path: ["dock", "show-process-indicators"],
    title: "起動中アプリのインジケータ",
    type: "boolean",
  },
  {
    defaultValue: false,
    desc: "Dock に最近使ったアプリを表示する。",
    group: "Dock",
    id: "dock.show-recents",
    path: ["dock", "show-recents"],
    recommended: true,
    title: "最近使ったアプリを Dock に表示",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "隠しているアプリを Dock 上で判別しやすくする。",
    group: "Dock",
    id: "dock.showhidden",
    path: ["dock", "showhidden"],
    title: "非表示アプリの Dock アイコンを半透明にする",
    type: "boolean",
  },
  {
    defaultValue: false,
    desc: "Dock を起動中アプリだけにする。",
    group: "Dock",
    id: "dock.static-only",
    path: ["dock", "static-only"],
    title: "開いているアプリだけを Dock に表示",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "トラックパッドの縦スワイプで Mission Control を表示する。",
    group: "Dock",
    id: "dock.showMissionControlGestureEnabled",
    path: ["dock", "showMissionControlGestureEnabled"],
    title: "Mission Control ジェスチャー",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "トラックパッドの縦スワイプで App Expose を表示する。",
    group: "Dock",
    id: "dock.showAppExposeGestureEnabled",
    path: ["dock", "showAppExposeGestureEnabled"],
    title: "App Expose ジェスチャー",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "4 本指の広げるジェスチャーでデスクトップを表示する。",
    group: "Dock",
    id: "dock.showDesktopGestureEnabled",
    path: ["dock", "showDesktopGestureEnabled"],
    title: "デスクトップ表示ジェスチャー",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "4 本指のピンチで Launchpad を表示する。",
    group: "Dock",
    id: "dock.showLaunchpadGestureEnabled",
    path: ["dock", "showLaunchpadGestureEnabled"],
    title: "Launchpad ジェスチャー",
    type: "boolean",
  },
  {
    defaultValue: 1,
    desc: "左上ホットコーナーの動作。",
    group: "Dock",
    id: "dock.wvous-tl-corner",
    path: ["dock", "wvous-tl-corner"],
    title: "ホットコーナー 左上",
    type: "enum",
    values: [
      {
        label: "disabled",
        value: 1,
      },
      {
        label: "Mission Control",
        value: 2,
      },
      {
        label: "Application Windows",
        value: 3,
      },
      {
        label: "Desktop",
        value: 4,
      },
      {
        label: "Start Screen Saver",
        value: 5,
      },
      {
        label: "Disable Screen Saver",
        value: 6,
      },
      {
        label: "Put Display to Sleep",
        value: 10,
      },
      {
        label: "Launchpad",
        value: 11,
      },
      {
        label: "Notification Center",
        value: 12,
      },
      {
        label: "Lock Screen",
        value: 13,
      },
      {
        label: "Quick Note",
        value: 14,
      },
    ],
  },
  {
    defaultValue: 1,
    desc: "右上ホットコーナーの動作。",
    group: "Dock",
    id: "dock.wvous-tr-corner",
    path: ["dock", "wvous-tr-corner"],
    title: "ホットコーナー 右上",
    type: "enum",
    values: [
      {
        label: "disabled",
        value: 1,
      },
      {
        label: "Mission Control",
        value: 2,
      },
      {
        label: "Application Windows",
        value: 3,
      },
      {
        label: "Desktop",
        value: 4,
      },
      {
        label: "Start Screen Saver",
        value: 5,
      },
      {
        label: "Disable Screen Saver",
        value: 6,
      },
      {
        label: "Put Display to Sleep",
        value: 10,
      },
      {
        label: "Launchpad",
        value: 11,
      },
      {
        label: "Notification Center",
        value: 12,
      },
      {
        label: "Lock Screen",
        value: 13,
      },
      {
        label: "Quick Note",
        value: 14,
      },
    ],
  },
  {
    defaultValue: 1,
    desc: "左下ホットコーナーの動作。",
    group: "Dock",
    id: "dock.wvous-bl-corner",
    path: ["dock", "wvous-bl-corner"],
    title: "ホットコーナー 左下",
    type: "enum",
    values: [
      {
        label: "disabled",
        value: 1,
      },
      {
        label: "Mission Control",
        value: 2,
      },
      {
        label: "Application Windows",
        value: 3,
      },
      {
        label: "Desktop",
        value: 4,
      },
      {
        label: "Start Screen Saver",
        value: 5,
      },
      {
        label: "Disable Screen Saver",
        value: 6,
      },
      {
        label: "Put Display to Sleep",
        value: 10,
      },
      {
        label: "Launchpad",
        value: 11,
      },
      {
        label: "Notification Center",
        value: 12,
      },
      {
        label: "Lock Screen",
        value: 13,
      },
      {
        label: "Quick Note",
        value: 14,
      },
    ],
  },
  {
    defaultValue: 13,
    desc: "右下ホットコーナーの動作。",
    group: "Dock",
    id: "dock.wvous-br-corner",
    path: ["dock", "wvous-br-corner"],
    title: "ホットコーナー 右下",
    type: "enum",
    values: [
      {
        label: "disabled",
        value: 1,
      },
      {
        label: "Mission Control",
        value: 2,
      },
      {
        label: "Application Windows",
        value: 3,
      },
      {
        label: "Desktop",
        value: 4,
      },
      {
        label: "Start Screen Saver",
        value: 5,
      },
      {
        label: "Disable Screen Saver",
        value: 6,
      },
      {
        label: "Put Display to Sleep",
        value: 10,
      },
      {
        label: "Launchpad",
        value: 11,
      },
      {
        label: "Notification Center",
        value: 12,
      },
      {
        label: "Lock Screen",
        value: 13,
      },
      {
        label: "Quick Note",
        value: 14,
      },
    ],
  },
  {
    defaultValue: -1,
    desc: "-1.0 でマウス加速度を無効化。通常は速度値として指定する。",
    group: "Trackpad/Mouse",
    id: ".GlobalPreferences.com.apple.mouse.scaling",
    path: [".GlobalPreferences", "com.apple.mouse.scaling"],
    title: "マウス追従速度",
    type: "number",
  },
  {
    defaultValue: true,
    desc: "トラックパッドのタップでクリックする。",
    group: "Trackpad/Mouse",
    id: "trackpad.Clicking",
    path: ["trackpad", "Clicking"],
    recommended: true,
    title: "タップでクリック",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "トラックパッドの 2 本指タップ/クリックを右クリックにする。",
    group: "Trackpad/Mouse",
    id: "trackpad.TrackpadRightClick",
    path: ["trackpad", "TrackpadRightClick"],
    recommended: true,
    title: "2 本指の右クリック",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "3 本指でウィンドウや項目をドラッグできるようにする。",
    group: "Trackpad/Mouse",
    id: "trackpad.TrackpadThreeFingerDrag",
    path: ["trackpad", "TrackpadThreeFingerDrag"],
    title: "3 本指ドラッグ",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "タップ操作からドラッグできるようにする。",
    group: "Trackpad/Mouse",
    id: "trackpad.Dragging",
    path: ["trackpad", "Dragging"],
    title: "タップでドラッグ",
    type: "boolean",
  },
  {
    defaultValue: false,
    desc: "ドラッグロックを有効にする。",
    group: "Trackpad/Mouse",
    id: "trackpad.DragLock",
    path: ["trackpad", "DragLock"],
    title: "ドラッグロック",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "トラックパッドの Force Click を抑制する。",
    group: "Trackpad/Mouse",
    id: "trackpad.ForceSuppressed",
    path: ["trackpad", "ForceSuppressed"],
    title: "Force Click を無効化",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "トラックパッドの触覚フィードバックを有効にする。",
    group: "Trackpad/Mouse",
    id: "trackpad.ActuateDetents",
    path: ["trackpad", "ActuateDetents"],
    title: "触覚フィードバック",
    type: "boolean",
  },
  {
    defaultValue: 1,
    desc: "0 でサイレントクリック、1 で通常。",
    group: "Trackpad/Mouse",
    id: "trackpad.ActuationStrength",
    path: ["trackpad", "ActuationStrength"],
    title: "クリック音の強さ",
    type: "enum",
    values: [
      {
        label: "silent",
        value: 0,
      },
      {
        label: "normal",
        value: 1,
      },
    ],
  },
  {
    defaultValue: 1,
    desc: "通常クリックの圧を light/medium/firm から選ぶ。",
    group: "Trackpad/Mouse",
    id: "trackpad.FirstClickThreshold",
    path: ["trackpad", "FirstClickThreshold"],
    title: "クリック圧",
    type: "enum",
    values: [
      {
        label: "light",
        value: 0,
      },
      {
        label: "medium",
        value: 1,
      },
      {
        label: "firm",
        value: 2,
      },
    ],
  },
  {
    defaultValue: 1,
    desc: "Force Touch の圧を light/medium/firm から選ぶ。",
    group: "Trackpad/Mouse",
    id: "trackpad.SecondClickThreshold",
    path: ["trackpad", "SecondClickThreshold"],
    title: "Force Touch の圧",
    type: "enum",
    values: [
      {
        label: "light",
        value: 0,
      },
      {
        label: "medium",
        value: 1,
      },
      {
        label: "firm",
        value: 2,
      },
    ],
  },
  {
    defaultValue: true,
    desc: "スクロール時の慣性を使う。",
    group: "Trackpad/Mouse",
    id: "trackpad.TrackpadMomentumScroll",
    path: ["trackpad", "TrackpadMomentumScroll"],
    title: "慣性スクロール",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "2 本指ピンチによるズームを有効にする。",
    group: "Trackpad/Mouse",
    id: "trackpad.TrackpadPinch",
    path: ["trackpad", "TrackpadPinch"],
    title: "2 本指ピンチ",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "2 本指の回転ジェスチャーを有効にする。",
    group: "Trackpad/Mouse",
    id: "trackpad.TrackpadRotate",
    path: ["trackpad", "TrackpadRotate"],
    title: "2 本指回転",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "2 本指ダブルタップでスマートズームする。",
    group: "Trackpad/Mouse",
    id: "trackpad.TrackpadTwoFingerDoubleTapGesture",
    path: ["trackpad", "TrackpadTwoFingerDoubleTapGesture"],
    title: "スマートズーム",
    type: "boolean",
  },
  {
    defaultValue: 2,
    desc: "3 本指横スワイプの動作。",
    group: "Trackpad/Mouse",
    id: "trackpad.TrackpadThreeFingerHorizSwipeGesture",
    path: ["trackpad", "TrackpadThreeFingerHorizSwipeGesture"],
    title: "3 本指横スワイプ",
    type: "enum",
    values: [
      {
        label: "disabled",
        value: 0,
      },
      {
        label: "between pages",
        value: 1,
      },
      {
        label: "full-screen apps",
        value: 2,
      },
    ],
  },
  {
    defaultValue: 2,
    desc: "3 本指縦スワイプで Mission Control/App Expose を使う。",
    group: "Trackpad/Mouse",
    id: "trackpad.TrackpadThreeFingerVertSwipeGesture",
    path: ["trackpad", "TrackpadThreeFingerVertSwipeGesture"],
    title: "3 本指縦スワイプ",
    type: "enum",
    values: [
      {
        label: "disabled",
        value: 0,
      },
      {
        label: "enabled",
        value: 2,
      },
    ],
  },
  {
    defaultValue: 2,
    desc: "4 本指横スワイプでフルスクリーンアプリを切り替える。",
    group: "Trackpad/Mouse",
    id: "trackpad.TrackpadFourFingerHorizSwipeGesture",
    path: ["trackpad", "TrackpadFourFingerHorizSwipeGesture"],
    title: "4 本指横スワイプ",
    type: "enum",
    values: [
      {
        label: "disabled",
        value: 0,
      },
      {
        label: "enabled",
        value: 2,
      },
    ],
  },
  {
    defaultValue: 2,
    desc: "4 本指縦スワイプで Mission Control/App Expose を使う。",
    group: "Trackpad/Mouse",
    id: "trackpad.TrackpadFourFingerVertSwipeGesture",
    path: ["trackpad", "TrackpadFourFingerVertSwipeGesture"],
    title: "4 本指縦スワイプ",
    type: "enum",
    values: [
      {
        label: "disabled",
        value: 0,
      },
      {
        label: "enabled",
        value: 2,
      },
    ],
  },
  {
    defaultValue: 2,
    desc: "4 本指ピンチ/広げる操作で Launchpad/デスクトップを使う。",
    group: "Trackpad/Mouse",
    id: "trackpad.TrackpadFourFingerPinchGesture",
    path: ["trackpad", "TrackpadFourFingerPinchGesture"],
    title: "4 本指ピンチ",
    type: "enum",
    values: [
      {
        label: "disabled",
        value: 0,
      },
      {
        label: "enabled",
        value: 2,
      },
    ],
  },
  {
    defaultValue: false,
    desc: "壁紙クリックでウィンドウを退避してデスクトップを表示する。",
    group: "Window Manager",
    id: "WindowManager.EnableStandardClickToShowDesktop",
    path: ["WindowManager", "EnableStandardClickToShowDesktop"],
    title: "壁紙クリックでデスクトップ表示",
    type: "boolean",
  },
  {
    defaultValue: false,
    desc: "ウィンドウタイル時に余白を付ける。",
    group: "Window Manager",
    id: "WindowManager.EnableTiledWindowMargins",
    path: ["WindowManager", "EnableTiledWindowMargins"],
    title: "タイル表示の余白",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "ウィンドウを画面端へドラッグしてタイル配置する。",
    group: "Window Manager",
    id: "WindowManager.EnableTilingByEdgeDrag",
    path: ["WindowManager", "EnableTilingByEdgeDrag"],
    title: "画面端ドラッグでタイル",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "Option キーを押しながらウィンドウをタイル配置する。",
    group: "Window Manager",
    id: "WindowManager.EnableTilingOptionAccelerator",
    path: ["WindowManager", "EnableTilingOptionAccelerator"],
    title: "Option キーでタイル",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "ウィンドウをメニューバーへドラッグして画面を埋める。",
    group: "Window Manager",
    id: "WindowManager.EnableTopTilingByEdgeDrag",
    path: ["WindowManager", "EnableTopTilingByEdgeDrag"],
    title: "上端ドラッグで最大化タイル",
    type: "boolean",
  },
  {
    defaultValue: false,
    desc: "Stage Manager を有効にする。",
    group: "Window Manager",
    id: "WindowManager.GloballyEnabled",
    path: ["WindowManager", "GloballyEnabled"],
    title: "Stage Manager",
    type: "boolean",
  },
  {
    defaultValue: false,
    desc: "通常デスクトップ上のアイコンを非表示にする。",
    group: "Window Manager",
    id: "WindowManager.StandardHideDesktopIcons",
    path: ["WindowManager", "StandardHideDesktopIcons"],
    title: "デスクトップアイコンを隠す",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "通常デスクトップ上のウィジェットを非表示にする。",
    group: "Window Manager",
    id: "WindowManager.StandardHideWidgets",
    path: ["WindowManager", "StandardHideWidgets"],
    title: "デスクトップウィジェットを隠す",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "メニューバーのバッテリー表示にパーセントを出す。",
    group: "Control Center",
    id: "controlcenter.BatteryShowPercentage",
    path: ["controlcenter", "BatteryShowPercentage"],
    recommended: true,
    title: "バッテリー残量をパーセント表示",
    type: "boolean",
  },
  {
    defaultValue: false,
    desc: "Control Center の AirDrop アイコン表示を切り替える。",
    group: "Control Center",
    id: "controlcenter.AirDrop",
    path: ["controlcenter", "AirDrop"],
    title: "AirDrop をメニューバーに表示",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "Control Center の Bluetooth アイコン表示を切り替える。",
    group: "Control Center",
    id: "controlcenter.Bluetooth",
    path: ["controlcenter", "Bluetooth"],
    title: "Bluetooth をメニューバーに表示",
    type: "boolean",
  },
  {
    defaultValue: false,
    desc: "Control Center の画面輝度アイコン表示を切り替える。",
    group: "Control Center",
    id: "controlcenter.Display",
    path: ["controlcenter", "Display"],
    title: "ディスプレイをメニューバーに表示",
    type: "boolean",
  },
  {
    defaultValue: false,
    desc: "Control Center の Focus アイコン表示を切り替える。",
    group: "Control Center",
    id: "controlcenter.FocusModes",
    path: ["controlcenter", "FocusModes"],
    title: "集中モードをメニューバーに表示",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "Now Playing アイコン表示を切り替える。",
    group: "Control Center",
    id: "controlcenter.NowPlaying",
    path: ["controlcenter", "NowPlaying"],
    title: "再生中をメニューバーに表示",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "Sound アイコン表示を切り替える。",
    group: "Control Center",
    id: "controlcenter.Sound",
    path: ["controlcenter", "Sound"],
    title: "サウンドをメニューバーに表示",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "メニューバー時計を 24 時間表示にする。",
    group: "Menu Clock",
    id: "menuExtraClock.Show24Hour",
    path: ["menuExtraClock", "Show24Hour"],
    recommended: true,
    title: "24 時間時計",
    type: "boolean",
  },
  {
    defaultValue: false,
    desc: "12 時間表示時の AM/PM を表示する。",
    group: "Menu Clock",
    id: "menuExtraClock.ShowAMPM",
    path: ["menuExtraClock", "ShowAMPM"],
    title: "AM/PM 表示",
    type: "boolean",
  },
  {
    defaultValue: 1,
    desc: "メニューバー時計の日付表示方法。",
    group: "Menu Clock",
    id: "menuExtraClock.ShowDate",
    path: ["menuExtraClock", "ShowDate"],
    recommended: true,
    title: "日付表示",
    type: "enum",
    values: [
      {
        label: "when space allows",
        value: 0,
      },
      {
        label: "always",
        value: 1,
      },
      {
        label: "never",
        value: 2,
      },
    ],
  },
  {
    defaultValue: true,
    desc: "メニューバー時計に日を表示する。",
    group: "Menu Clock",
    id: "menuExtraClock.ShowDayOfMonth",
    path: ["menuExtraClock", "ShowDayOfMonth"],
    recommended: true,
    title: "日を表示",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "メニューバー時計に曜日を表示する。",
    group: "Menu Clock",
    id: "menuExtraClock.ShowDayOfWeek",
    path: ["menuExtraClock", "ShowDayOfWeek"],
    recommended: true,
    title: "曜日を表示",
    type: "boolean",
  },
  {
    defaultValue: false,
    desc: "メニューバー時計に秒を表示する。",
    group: "Menu Clock",
    id: "menuExtraClock.ShowSeconds",
    path: ["menuExtraClock", "ShowSeconds"],
    title: "秒を表示",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "ウィンドウスクリーンショットのドロップシャドウを消す。",
    group: "Screenshots",
    id: "screencapture.disable-shadow",
    path: ["screencapture", "disable-shadow"],
    recommended: true,
    title: "スクリーンショットの影を無効化",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "スクリーンショットのファイル名に日付時刻を含める。",
    group: "Screenshots",
    id: "screencapture.include-date",
    path: ["screencapture", "include-date"],
    title: "ファイル名に日付を含める",
    type: "boolean",
  },
  {
    defaultValue: "/Users/you/Desktop",
    desc: "スクリーンショットの保存先パス。",
    group: "Screenshots",
    id: "screencapture.location",
    path: ["screencapture", "location"],
    title: "保存先",
    type: "text",
  },
  {
    defaultValue: false,
    desc: "スクリーンショット撮影後にサムネイルを表示する。",
    group: "Screenshots",
    id: "screencapture.show-thumbnail",
    path: ["screencapture", "show-thumbnail"],
    recommended: true,
    title: "撮影後のサムネイル表示",
    type: "boolean",
  },
  {
    defaultValue: "file",
    desc: "スクリーンショットの保存先タイプを選ぶ。",
    group: "Screenshots",
    id: "screencapture.target",
    path: ["screencapture", "target"],
    title: "保存ターゲット",
    type: "enum",
    values: [
      {
        label: "file",
        value: "file",
      },
      {
        label: "clipboard",
        value: "clipboard",
      },
      {
        label: "preview",
        value: "preview",
      },
      {
        label: "mail",
        value: "mail",
      },
      {
        label: "messages",
        value: "messages",
      },
    ],
  },
  {
    defaultValue: "png",
    desc: "スクリーンショットの画像形式。",
    group: "Screenshots",
    id: "screencapture.type",
    path: ["screencapture", "type"],
    title: "画像形式",
    type: "enum",
    values: [
      {
        label: "png",
        value: "png",
      },
      {
        label: "jpg",
        value: "jpg",
      },
      {
        label: "pdf",
        value: "pdf",
      },
      {
        label: "tiff",
        value: "tiff",
      },
      {
        label: "gif",
        value: "gif",
      },
    ],
  },
  {
    defaultValue: true,
    desc: "ダウンロードしたアプリの quarantine を有効にする。",
    group: "Security",
    id: "LaunchServices.LSQuarantine",
    path: ["LaunchServices", "LSQuarantine"],
    title: "ダウンロードアプリの quarantine",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "スクリーンセーバ停止または解除時にパスワードを求める。",
    group: "Security",
    id: "screensaver.askForPassword",
    path: ["screensaver", "askForPassword"],
    recommended: true,
    title: "スクリーンセーバ解除時にパスワード要求",
    type: "boolean",
  },
  {
    defaultValue: 0,
    desc: "パスワード要求までの秒数。",
    group: "Security",
    id: "screensaver.askForPasswordDelay",
    path: ["screensaver", "askForPasswordDelay"],
    recommended: true,
    title: "パスワード要求までの猶予",
    type: "number",
  },
  {
    defaultValue: false,
    desc: "macOS ソフトウェアアップデートを自動でインストールする。",
    group: "Security",
    id: "SoftwareUpdate.AutomaticallyInstallMacOSUpdates",
    path: ["SoftwareUpdate", "AutomaticallyInstallMacOSUpdates"],
    title: "macOS アップデートを自動インストール",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "画面切替やアプリ起動時のアニメーションを減らす。",
    group: "Accessibility",
    id: "universalaccess.reduceMotion",
    path: ["universalaccess", "reduceMotion"],
    title: "視差効果を減らす",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "メニューバーなどの透明度を下げる。",
    group: "Accessibility",
    id: "universalaccess.reduceTransparency",
    path: ["universalaccess", "reduceTransparency"],
    title: "透明度を下げる",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "Control キーを押しながらスクロールしてズームする。",
    group: "Accessibility",
    id: "universalaccess.closeViewScrollWheelToggle",
    path: ["universalaccess", "closeViewScrollWheelToggle"],
    title: "Control + スクロールでズーム",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "ズーム中にキーボードフォーカスへ追従する。",
    group: "Accessibility",
    id: "universalaccess.closeViewZoomFollowsFocus",
    path: ["universalaccess", "closeViewZoomFollowsFocus"],
    title: "ズーム中にフォーカスへ追従",
    type: "boolean",
  },
  {
    defaultValue: 1.25,
    desc: "カーソルサイズを指定する。1 が標準、4 が最大。",
    group: "Accessibility",
    id: "universalaccess.mouseDriverCursorSize",
    path: ["universalaccess", "mouseDriverCursorSize"],
    title: "カーソルサイズ",
    type: "number",
  },
  {
    defaultValue: true,
    desc: "Activity Monitor 起動時のメインウィンドウ表示を切り替える。",
    group: "Apps",
    id: "ActivityMonitor.OpenMainWindow",
    path: ["ActivityMonitor", "OpenMainWindow"],
    title: "Activity Monitor 起動時にメインウィンドウを開く",
    type: "boolean",
  },
  {
    defaultValue: 5,
    desc: "Dock アイコンに表示する情報を選ぶ。",
    group: "Apps",
    id: "ActivityMonitor.IconType",
    path: ["ActivityMonitor", "IconType"],
    title: "Activity Monitor の Dock アイコン",
    type: "enum",
    values: [
      {
        label: "application icon",
        value: 0,
      },
      {
        label: "network usage",
        value: 2,
      },
      {
        label: "disk activity",
        value: 3,
      },
      {
        label: "CPU usage",
        value: 5,
      },
      {
        label: "CPU history",
        value: 6,
      },
    ],
  },
  {
    defaultValue: 100,
    desc: "プロセス一覧に表示するカテゴリを選ぶ。",
    group: "Apps",
    id: "ActivityMonitor.ShowCategory",
    path: ["ActivityMonitor", "ShowCategory"],
    title: "Activity Monitor の表示対象",
    type: "enum",
    values: [
      {
        label: "all processes",
        value: 100,
      },
      {
        label: "all hierarchical",
        value: 101,
      },
      {
        label: "my processes",
        value: 102,
      },
      {
        label: "system processes",
        value: 103,
      },
      {
        label: "active processes",
        value: 105,
      },
      {
        label: "windowed processes",
        value: 107,
      },
    ],
  },
  {
    defaultValue: "CPUUsage",
    desc: "メイン画面の初期ソート列。",
    group: "Apps",
    id: "ActivityMonitor.SortColumn",
    path: ["ActivityMonitor", "SortColumn"],
    title: "Activity Monitor のソート列",
    type: "text",
  },
  {
    defaultValue: 0,
    desc: "0 は降順。",
    group: "Apps",
    id: "ActivityMonitor.SortDirection",
    path: ["ActivityMonitor", "SortDirection"],
    title: "Activity Monitor のソート方向",
    type: "enum",
    values: [
      {
        label: "descending",
        value: 0,
      },
      {
        label: "ascending",
        value: 1,
      },
    ],
  },
  {
    defaultValue: "Monday",
    desc: "Calendar.app の週の開始曜日。",
    group: "Apps",
    id: "iCal.first day of week",
    path: ["iCal", "first day of week"],
    title: "Calendar の週の開始曜日",
    type: "enum",
    values: [
      {
        label: "System Setting",
        value: "System Setting",
      },
      {
        label: "Sunday",
        value: "Sunday",
      },
      {
        label: "Monday",
        value: "Monday",
      },
      {
        label: "Tuesday",
        value: "Tuesday",
      },
      {
        label: "Wednesday",
        value: "Wednesday",
      },
      {
        label: "Thursday",
        value: "Thursday",
      },
      {
        label: "Friday",
        value: "Friday",
      },
      {
        label: "Saturday",
        value: "Saturday",
      },
    ],
  },
  {
    defaultValue: true,
    desc: "Calendar.app のカレンダー一覧を表示する。",
    group: "Apps",
    id: "iCal.CalendarSidebarShown",
    path: ["iCal", "CalendarSidebarShown"],
    title: "Calendar のサイドバー",
    type: "boolean",
  },
  {
    defaultValue: false,
    desc: "ゲストアカウントでのログインを許可する。",
    group: "Login Window",
    id: "loginwindow.GuestEnabled",
    path: ["loginwindow", "GuestEnabled"],
    recommended: true,
    title: "ゲストログイン",
    type: "boolean",
  },
  {
    defaultValue: false,
    desc: "ユーザー一覧ではなく名前とパスワード欄を表示する。",
    group: "Login Window",
    id: "loginwindow.SHOWFULLNAME",
    path: ["loginwindow", "SHOWFULLNAME"],
    title: "ログイン画面を名前とパスワード入力にする",
    type: "boolean",
  },
  {
    defaultValue: true,
    desc: "ログイン画面で >console と入力してコンソールへ入る機能を無効にする。",
    group: "Login Window",
    id: "loginwindow.DisableConsoleAccess",
    path: ["loginwindow", "DisableConsoleAccess"],
    title: "console ログインを無効化",
    type: "boolean",
  },
  {
    defaultValue: "Change Input Source",
    desc: "Fn キーを押したときの動作を選ぶ。",
    group: "Other",
    id: "hitoolbox.AppleFnUsageType",
    path: ["hitoolbox", "AppleFnUsageType"],
    title: "Fn キーの動作",
    type: "enum",
    values: [
      {
        label: "emoji and symbols",
        value: "Show Emoji & Symbols",
      },
      {
        label: "change input source",
        value: "Change Input Source",
      },
      {
        label: "start dictation",
        value: "Start Dictation",
      },
      {
        label: "do nothing",
        value: "Do Nothing",
      },
    ],
  },
  {
    defaultValue: "TwoButton",
    desc: "Magic Mouse で右クリックを使うかを選ぶ。",
    group: "Other",
    id: "magicmouse.MouseButtonMode",
    path: ["magicmouse", "MouseButtonMode"],
    title: "Magic Mouse のボタンモード",
    type: "enum",
    values: [
      {
        label: "two buttons",
        value: "TwoButton",
      },
      {
        label: "one button",
        value: "OneButton",
      },
    ],
  },
  {
    defaultValue: false,
    desc: "true で 1 つの Space が全ディスプレイにまたがる。",
    group: "Other",
    id: "spaces.spans-displays",
    path: ["spaces", "spans-displays"],
    title: "Spaces と複数ディスプレイ",
    type: "boolean",
  },
] as const satisfies readonly DefaultsOption[];
